# Simple Linear Regression With scikit-learn

**Step1: import packages and classes**

In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

**Step2: Providing the data**

In [6]:
x=np.array([5,15,25,35,45,55]).reshape((-1,1))
y=np.array([5,20,14,32,22,38])

In [7]:
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [8]:
y

array([ 5, 20, 14, 32, 22, 38])

**Step3: Create a model and fit it**

In [10]:
model = LinearRegression()
model.fit(x,y)

LinearRegression()

**Step4: Get the results**

In [12]:
r_sq=model.score(x,y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.715875613747954


In [13]:
print(f"intercept: {model.intercept_}")
print(f"slope: {model.coef_}")

intercept: 5.633333333333333
slope: [0.54]


In [15]:
new_model = LinearRegression().fit(x,y.reshape((-1,1)))
print(f"intercept: {model.intercept_}")
print(f"slope: {model.coef_}")

intercept: 5.633333333333333
slope: [0.54]


**Step5: Predict response**

In [16]:
y_pred=model.predict(x)
print(f"predict response: \n{y_pred}")

predict response: 
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [17]:
y_pred=model.intercept_+model.coef_*x
print(f"predict response: \n{y_pred}")

predict response: 
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


# Multiple Linear Regression with Scikit-learn

**Step1 and 2: import the package and classes, and provide data** 

In [19]:
import numpy as np
from sklearn.linear_model import LinearRegression
x=[[0,1],[5,1],[15,2],[25,5],[35,11],[45,15],[55,34],[60,35]]
y=[4,5,20,14,32,22,38,43]

In [20]:
x,y=np.array(x), np.array(y)

In [21]:
x

array([[ 0,  1],
       [ 5,  1],
       [15,  2],
       [25,  5],
       [35, 11],
       [45, 15],
       [55, 34],
       [60, 35]])

In [22]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

**Step3: create a model and fit it**

In [23]:
model = LinearRegression().fit(x,y)

**Step4: Get the result**

In [26]:
r_sq = model.score(x,y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.8615939258756776


In [27]:
print(f"intercept: {model.intercept_}")
print(f"slope: {model.coef_}")

intercept: 5.52257927519819
slope: [0.44706965 0.25502548]


**Step5 : predict response**

In [28]:
y_pred = model.predict(x)
print(f"predict response: \n{y_pred}")

predict response: 
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [30]:
# using coefficient of determination
y_pred = model.intercept_ + np.sum(model.coef_*x, axis = 1)
print(f"predict response: \n{y_pred}")

predict response: 
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


# Polynominal Linear Regression with Scikit-learn

**Step1 and 2: import the paclage and classes and provide data** 

In [32]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

**Step2a: provide data**

In [34]:
x=np.array([5,15,25,35,45,55]).reshape((-1,1))
y=np.array([15,11,2,8,25,32])

**Step2b: transform input data**

In [36]:
transformer = PolynomialFeatures(degree = 2, include_bias=False)

In [40]:
transformer.fit(x)

PolynomialFeatures(include_bias=False)

In [41]:
x_ = transformer.transform(x)

In [44]:
x_ = PolynomialFeatures(degree = 2, include_bias=False).fit_transform(x)

In [45]:
x_

array([[   5.,   25.],
       [  15.,  225.],
       [  25.,  625.],
       [  35., 1225.],
       [  45., 2025.],
       [  55., 3025.]])